### ISSUE TITLE
Issue-added send tx request

### ISSUE THREAD

**Issue by Zeusofsky** [Zeusofsky/node-connector#10]
Automated Review Comments
Issues in foundation/tcp/tcp.go:
  - (5, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
Issues in qubic.go:
  - (1, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')

**Comment by Oyase-shinobi** [comment]
I got it.
