### ISSUE TITLE
Issue-first commit

### ISSUE THREAD

**Issue by Zeusofsky** [Zeusofsky/node-connector#2]
Automated Review Comments
Issues in balance.go:
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in foundation/tcp/conn.go:
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
Issues in foundation/tcp/request.go:
  - (16, 'Line exceeds 80 characters')
Issues in foundation/tcp/tcp.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
Issues in go.sum:
  - (3, 'Line exceeds 80 characters')
Issues in qubic.go:
  - (5, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')

**Comment by glory1001** [comment]
I got it.
