### ISSUE TITLE
Issue-added gettickinfo, getticktransactions, gettickdata, sendrawtransaction

### ISSUE THREAD

**Issue by Zeusofsky** [Zeusofsky/node-connector#6]
Automated Review Comments
Issues in data/tick/tick.go:
  - (39, 'Line exceeds 80 characters')
Issues in foundation/tcp/conn.go:
  - (1, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in foundation/tcp/tcp.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
Issues in foundation/wallet/id.go:
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
Issues in foundation/wallet/wallet.go:
  - (23, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
Issues in foundation/wallet/wallet_test.go:
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
Issues in go.sum:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
Issues in qubic.go:
  - (4, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (142, 'Hardcoded string found')

**Comment by Muray1008** [comment]
I got it.
