### ISSUE TITLE
Issue-added gettxstatus

### ISSUE THREAD

**Issue by Zeusofsky** [Zeusofsky/node-connector#8]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
Issues in data/tick/tick.go:
  - (4, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in foundation/tcp/conn.go:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
Issues in qubic.go:
  - (4, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')

**Comment by Oyase-shinobi** [comment]
I got it.
